SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS board;

CREATE TABLE `board` (
    `no` INT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `user_no` INT NOT NULL COMMENT 'FK',
    `group_no` INT DEFAULT 1 COMMENT 'FK',
    `place_no` INT DEFAULT NULL COMMENT 'FK',
    `rating` DOUBLE DEFAULT 0.0 COMMENT '평점',
    `title` VARCHAR(200) NOT NULL COMMENT '제목',
    `content` TEXT COMMENT '내용',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`no`),
    FOREIGN KEY (`user_no`) REFERENCES `users`(`no`) ON DELETE CASCADE,
    FOREIGN KEY (`group_no`) REFERENCES `board_group`(`no`) ON DELETE CASCADE,
    FOREIGN KEY (`place_no`) REFERENCES `place`(`no`) ON DELETE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;