DROP TABLE IF EXISTS `board_group`;

CREATE TABLE `board_group` (
    `no` INT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `name` VARCHAR(100) NOT NULL COMMENT '게시판 명',
    `seq` INT NOT NULL COMMENT '순서',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`no`),
);