SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS review_comment;

CREATE TABLE `review_comment` (
    `no` INT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `board_no` INT NOT NULL COMMENT 'FK: 게시글 번호',
    `user_no` INT NOT NULL COMMENT 'FK: 작성자 번호',
    `content` TEXT NOT NULL COMMENT '댓글 내용',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`no`),
    FOREIGN KEY (`board_no`) REFERENCES `board`(`no`) ON DELETE CASCADE,
    FOREIGN KEY (`user_no`) REFERENCES `users`(`no`) ON DELETE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;